// list generated with ChatGPT
const workoutOptions = [
  { exercise: "Bench Press", units: ["lbs", "kgs"], reps: true },
  { exercise: "Deadlift", units: ["lbs", "kgs"], reps: true },
  { exercise: "Squat", units: ["lbs", "kgs"], reps: true },
  { exercise: "Overhead Press", units: ["lbs", "kgs"], reps: true },
  { exercise: "Barbell Row", units: ["lbs", "kgs"], reps: true },
  { exercise: "Pull-Up", units: [], reps: true },
  { exercise: "Push-Up", units: [], reps: true },
  { exercise: "Plank", units: ["time"], reps: false },
  { exercise: "Leg Press", units: ["lbs", "kgs"], reps: true },
  { exercise: "Lunges", units: ["lbs", "kgs"], reps: true },
  { exercise: "Bicep Curl", units: ["lbs", "kgs"], reps: true },
  { exercise: "Tricep Extension", units: ["lbs", "kgs"], reps: true },
  { exercise: "Lat Pull-Down", units: ["lbs", "kgs"], reps: true },
  { exercise: "Box Jump", units: ["inches", "cm"], reps: true },
  { exercise: "Burpees", units: [], reps: true },
  { exercise: "Mountain Climbers", units: [], reps: true },
  { exercise: "Skipping", units: ["time"], reps: false },
  { exercise: "Rowing Machine", units: ["meters", "time"], reps: false },
  {
    exercise: "Stationary Bike",
    units: ["km", "miles", "time"],
    reps: false,
  },
  {
    exercise: "Elliptical Machine",
    units: ["km", "miles", "time"],
    reps: false,
  },
  { exercise: "Dumbbell Flies", units: ["lbs", "kgs"], reps: true },
  { exercise: "Hammer Curls", units: ["lbs", "kgs"], reps: true },
  { exercise: "Front Squats", units: ["lbs", "kgs"], reps: true },
  { exercise: "Back Squats", units: ["lbs", "kgs"], reps: true },
  { exercise: "Sumo Deadlift", units: ["lbs", "kgs"], reps: true },
  { exercise: "Romanian Deadlift", units: ["lbs", "kgs"], reps: true },
  { exercise: "Calf Raises", units: ["lbs", "kgs"], reps: true },
  { exercise: "Shoulder Shrugs", units: ["lbs", "kgs"], reps: true },
  { exercise: "T-Bar Row", units: ["lbs", "kgs"], reps: true },
  { exercise: "Face Pulls", units: ["lbs", "kgs"], reps: true },
  { exercise: "Russian Twists", units: ["lbs", "kgs"], reps: true },
  { exercise: "Leg Raises", units: [], reps: true },
  { exercise: "Sit-Ups", units: [], reps: true },
  { exercise: "Crunches", units: [], reps: true },
  { exercise: "Kettlebell Swings", units: ["lbs", "kgs"], reps: true },
  { exercise: "Turkish Get-Up", units: ["lbs", "kgs"], reps: true },
  { exercise: "Farmer's Walk", units: ["lbs", "kgs"], reps: false },
  { exercise: "Battle Ropes", units: ["lbs", "kgs", "time"], reps: false },
  { exercise: "Jump Rope", units: ["time"], reps: false },
  { exercise: "Sled Push", units: ["lbs", "kgs", "meters"], reps: false },
  { exercise: "Sled Pull", units: ["lbs", "kgs", "meters"], reps: false },
  { exercise: "Wall Ball Shots", units: ["lbs", "kgs"], reps: true },
  { exercise: "Thrusters", units: ["lbs", "kgs"], reps: true },
  { exercise: "Power Clean", units: ["lbs", "kgs"], reps: true },
  { exercise: "Clean and Jerk", units: ["lbs", "kgs"], reps: true },
  { exercise: "Snatch", units: ["lbs", "kgs"], reps: true },
  { exercise: "Muscle-Up", units: [], reps: true },
  { exercise: "Handstand Push-Up", units: [], reps: true },
  { exercise: "Pistol Squat", units: [], reps: true },
  { exercise: "Yoga", units: ["time"], reps: false },
  { exercise: "Pilates", units: ["time"], reps: false },
  { exercise: "Tai Chi", units: ["time"], reps: false },
  { exercise: "Swimming", units: ["meters", "yards", "time"], reps: false },
  { exercise: "Running", units: ["km", "miles", "time"], reps: false },
  { exercise: "Cycling", units: ["km", "miles", "time"], reps: false },
  { exercise: "Hiking", units: ["km", "miles"], reps: false },
  {
    exercise: "Stair Climber Machine",
    units: ["steps", "time"],
    reps: false,
  },
  { exercise: "Jumping Jacks", units: [], reps: true },
  { exercise: "High Knees", units: [], reps: true },
  { exercise: "Tuck Jumps", units: [], reps: true },
];

export { workoutOptions };
